from keras_autodoc.autogen import generate
from docs.autogen import keras_dir, clean_module_name, post_process_signature
from docs.autogen import add_np_implementation
from docs.structure import PAGES, EXCLUDE
from keras.layers import Input
import shutil
import os

from pathlib import Path


def preprocess_docstring(docstring, function, signature):
    if "backend" in signature and "{{np_implementation}}" in docstring:
        docstring = add_np_implementation(function, docstring)
    return docstring


def fix_keras_pages():
    for page in PAGES:
        if not page['page'] == 'layers/core.md':
            continue
        page['classes'].remove(Input)
        page['functions'] = [Input]


def make_keras_docs(dest_dir):

    fix_keras_pages()
    dest_dir = Path(dest_dir)
    template_dir = keras_dir / "docs" / "templates"
    generate(
        dest_dir,
        template_dir,
        PAGES,
        'https://github.com/keras-team/keras/blob/master',
        keras_dir / "examples",
        EXCLUDE,
        clean_module_name=clean_module_name,
        post_process_signature=post_process_signature,
        preprocess_docstring=preprocess_docstring,
    )
    readme = (keras_dir / "README.md").read_text()
    index = (template_dir / "index.md").read_text()
    index = index.replace("{{autogenerated}}", readme[readme.find("##"):])
    (dest_dir / "index.md").write_text(index, encoding="utf-8")
    shutil.copyfile(keras_dir / "CONTRIBUTING.md", dest_dir / "contributing.md")


def test_docs_in_custom_destination_dir(tmpdir):
    make_keras_docs(tmpdir)
    tmpdir = Path(tmpdir)
    assert (tmpdir / "layers").is_dir()
    assert (tmpdir / "models").is_dir()
    assert (tmpdir / "examples").is_dir()
    assert "for easy and fast" in (tmpdir / "index.md").read_text()
    assert os.listdir(tmpdir / "examples")
    text = []
    for file_path in get_all_files(tmpdir):
        text.append(file_path.read_text())
    text = "\n".join(text)
    assert "keras_applications" not in text
    assert "keras_preprocessing" not in text
    assert "keras.layers.core" not in text
    assert "layers.pooling" not in text
    assert "utils.np_utils" not in text
    assert "backend.tensorflow_backend" not in text
    assert (
        "keras.layers.Dense(units, activation=None, use_bias=True, "
        "kernel_initializer='glorot_uniform', bias_initializer='zeros', "
        "kernel_regularizer=None, bias_regularizer=None, "
        "activity_regularizer=None, kernel_constraint=None, "
        "bias_constraint=None)"
    ) in text

    assert (
        '```python\n'
        '# as first layer in a sequential model:\n'
        'model = Sequential()\n'
        'model.add(Dense(32, input_shape=(16,)))\n'
        '# now the model will take as input arrays of shape (*, 16)\n'
        '# and output arrays of shape (*, 32)\n'
        '\n'
        '# after the first layer, you don\'t need to specify\n'
        '# the size of the input anymore:\n'
        'model.add(Dense(32))\n'
    ) in text
    assert "keras.layers.Dense" in text
    assert "__Numpy implementation__" in (tmpdir / 'backend.md').read_text()


def get_all_files(directory):
    for root, dirs, files in os.walk(directory):
        root = Path(root)
        for f in files:
            yield root / f
